/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-04 08:40:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>在线作业管理系统</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" charset=\"utf-8\">\r\n");
      out.write("\t<!-- 引入bootstrap -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/bootstrap.min.css\">\r\n");
      out.write("\t<!-- 引入JQuery  bootstrap.js-->\r\n");
      out.write("\t<script src=\"./js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"./js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"./js/login.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 顶栏 -->\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 顶栏 -->\r\n");
      out.write("<div class=\"container\" id=\"top\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-12\">\r\n");
      out.write("            <!--加入导航条标--->\r\n");
      out.write("\t\t\t<div id=\"\" class=\"ass\">\r\n");
      out.write("\t\t\t\t<h1 style=\"color:red\">在线作业管理系统</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("            <div class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("                　<div class=\"navbar-header\">\r\n");
      out.write("                　    <a href=\"##\" class=\"navbar-brand\" >首页</a>\r\n");
      out.write("                　</div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 中间主体 -->\r\n");
      out.write("\t<div class=\"container\" id=\"content\" >\r\n");
      out.write("\t\t\t<div class=\"row\" >\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-2\">\r\n");
      out.write("    <ul class=\"nav nav-pills nav-stacked\" id=\"nav\" style=\"  border:1px solid #999999;height: 200px; width: 270px; line-height: 2em; padding-left: 10px; \">\r\n");
      out.write("       \r\n");
      out.write("\t\t<li><h4 style=\"color:blue \">用户登录</h4></li>\r\n");
      out.write("\t \r\n");
      out.write("        <li><p>教师用教师号登录（学生用学生号登录）</p></li>\r\n");
      out.write("        <li> 用户名:<input type=\"text\" id=\"uname\"  placeholder=\"请输入用户名\" name=\"uname\"></li>\r\n");
      out.write("\t\t<li>密码:&nbsp;&nbsp;&nbsp;<input id=\"upass\" type=\"password\" placeholder=\"请输入密码\" name=\"upass\"></li>\r\n");
      out.write("\t\t<li>身份:\r\n");
      out.write("\t\t<select id=\"userRole\" >\r\n");
      out.write("\t\t\t<option value=\"1\">老师</option>\r\n");
      out.write("\t\t\t<option value=\"2\">学生</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<button  class=\"btn btn-default btn-info\" onclick=\"login()\">登录</button>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"nav nav-pills nav-stacked\" id=\"nav\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-top: 5px; border: 1px solid #999999; width: 270px; padding-left: 10px; line-height: 2em;\">\r\n");
      out.write("\t\t\t\t\t<li><h4 style=\"color: blue\">网站公告</h4></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t<ul class=\"nav nav-pills nav-stacked\" id=\"nav\" style=\" margin-top: 5px; border:1px solid #999999; width: 270px; padding-left: 10px; line-height: 2em; \">\r\n");
      out.write("\t\t<li><h4 style=\"color:blue\">日历表</h4></li>\r\n");
      out.write("\t\t<li><!-- On rows -->\r\n");
      out.write("\t\t\t<tr >日</tr>\r\n");
      out.write("\t\t\t<tr >一</tr>\r\n");
      out.write("\t\t\t<tr >二</tr>\r\n");
      out.write("\t\t\t<tr >三</tr>\r\n");
      out.write("\t\t\t<tr >四</tr>\r\n");
      out.write("\t\t\t<tr >五</tr>\r\n");
      out.write("\t\t\t<tr >六</tr>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t<li><!-- On rows -->\r\n");
      out.write("\t\t\t<tr >4</tr>\r\n");
      out.write("\t\t\t<tr >5</tr>\r\n");
      out.write("\t\t\t<tr >6</tr>\r\n");
      out.write("\t\t\t<tr >7</tr>\r\n");
      out.write("\t\t\t<tr >8</tr>\r\n");
      out.write("\t\t\t<tr >9</tr>\r\n");
      out.write("\t\t\t<tr >10</tr>\r\n");
      out.write("\t\t\t</li>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-10\" >\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\" style=\" border:1px solid #999999; height: 470px; width: 863px;margin-left: 80px;  \">\r\n");
      out.write("\t\t\t\t    <div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h4 style=\"color:blue\">教学基本资料</h4>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    <table  class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t        <tbody id=\"materialBody\">\r\n");
      out.write("\t\t\t\t\t        </tbody>\r\n");
      out.write("\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t    </table>\r\n");
      out.write("\t\t\t\t    <nav id=\"mtpagination2\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal fade\" id=\"materialContent\" tabindex=\"-1\"\r\n");
      out.write("\t\t\trole=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\" style=\"width: 500px; height: 330px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<h2>教学材料内容:</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"materialContentdiv\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<div class=\"container\" id=\"footer\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t.ass{\r\n");
      out.write("\t\t\tbackground-color: #888888;\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t\theight:55px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tchangeMaterialsPage(1,0);\r\n");
      out.write("\t})\r\n");
      out.write("\tfunction watchContent(materialId) {\r\n");
      out.write("\r\n");
      out.write("\tvar content;\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"/homeworkMIS/getMaterialContent.tm\",\r\n");
      out.write("\t\tasync : false,\r\n");
      out.write("\t\tmethod : \"get\",\r\n");
      out.write("\t\tdata : {\r\n");
      out.write("\t\t\t\"id\" : materialId\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\tcontent = data;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#materialContentdiv\").html(content);\r\n");
      out.write("\t$('#materialContent').modal();\r\n");
      out.write("}\r\n");
      out.write("\tfunction changeMaterialsPage(page, pageChange) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\taysnc : false,\r\n");
      out.write("\t\t\turl : \"/homeworkMIS/getPagerMaterials.tm\",\r\n");
      out.write("\t\t\tcache : false,\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\"pageChange\" : pageChange,\r\n");
      out.write("\t\t\t\t\"page\" : page\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tif (data == null || data == '') {\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tvar str = \"\"\r\n");
      out.write("\t\t\t\t\tfor (var i = 0; i < data.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tstr += \"<tr id='mt\" + data[i].id + \"'><td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ data[i].headline\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</td><td><a href='#' onclick='watchContent(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ data[i].id + \")'>查看内容</a>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</td><td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ data[i].uploadDate\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tvar str2=\"\" ;\r\n");
      out.write("\t\t\t\t\t$. ajax({ \r\n");
      out.write("\t\t\t\t\t\tcache: false,\r\n");
      out.write("\t\t\t\t\t\tasync:false ,\r\n");
      out.write("\t\t\t\t\t\turl:\"/homeworkMIS/getMaterialsNum.tm\",\r\n");
      out.write("\t\t\t\t\t\tmethod:\"get\",\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\t\tstr2 += \"<ul class='pagination'>\" +\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"<li> <a href='#' onclick='changeMaterialsPage(-1,1)'>.上一页</a></li>\";\r\n");
      out.write("\t\t\t\t\t\t\tfor(var i = 0;i<=data/7.00000000001; i++){\r\n");
      out.write("\t\t\t\t\t\t\t\tstr2 += \"<li> <a href='#' onclick='changeMaterialsPage(\"+(i+1)+\" ,0)'>\"+(i+1)+\"</a></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tstr2 += \"<li> <a href='#' onclick='changeMaterialsPage(1,1)'>下一页</a></1i></ul>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t$(\"#mtpagination2\").html(str2);\r\n");
      out.write("\t\t\t\t\t$(\"#materialBody\").html(str);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
