/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-04-02 08:48:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class laboratory_002dmanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"laboratorytable\" style=\"width: 1200px;\" />\r\n");
      out.write("\t<div id=\"laboratory_tb\">\r\n");
      out.write("\t\t<div class=\"laboratorysToolbar_button\"></div>\r\n");
      out.write("\t\t<a href=\"#\" data-options=\"iconCls:'icon-add'\" id=\"addbutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"addLaboratory()\">添加</a> &nbsp; <a\r\n");
      out.write("\t\t\thref=\"#\" data-options=\"iconCls:'icon-save'\" id=\"updatebutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"updateLaboratory()\">修改</a>&nbsp;\r\n");
      out.write("\t\t<a href=\"#\" data-options=\"iconCls:'icon-remove'\" id=\"removebutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"deleteLaboratory()\">删除</a> &nbsp;\r\n");
      out.write("\t\t<a href=\"#\" data-options=\"iconCls:'icon-cancel'\" id=\"cancelbutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"cancel()\">取消选择</a> &nbsp; <a\r\n");
      out.write("\t\t\thref=\"#\" data-options=\"iconCls:'icon-undo'\" id=\"refreshbutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"refreshTable()\">刷新</a>\r\n");
      out.write("\t\t&nbsp;实验室名:\r\n");
      out.write("\t\t<div id=\"searcher_laboratoryName\" prompt=\"实验室名字...\" class=\"easyui-textbox\"></div>\r\n");
      out.write("\t\t&nbsp; <a href=\"#\" data-options=\"iconCls:'icon-search'\" id=\"searcherbutton\" class=\"easyui-linkbutton\">搜索</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 增加的提示框 -->\r\n");
      out.write("\t<div id=\"laboratorys_dialog\" class=\"easyui-dialog\"\r\n");
      out.write("\t\tdata-options=\"closed:true,iconCls:'icon-save'\"\r\n");
      out.write("\t\tstyle=\"width: 350px; height: 250px; padding: 10px;\">\r\n");
      out.write("\t\t<input id=\"id\" name=\"id\" type=\"hidden\" />\r\n");
      out.write("\t\t<form id=\"laboratory_dialog_form\" method=\"post\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">实验室名 </td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"laboratoryName\"\r\n");
      out.write("\t\t\t\t\t\tname=\"laboratoryName\" class=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">实验室编号</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"laboratoryId\"\r\n");
      out.write("\t\t\t\t\t\tname=\"laboratoryId\" class=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">实验室座位数量</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"laboratorySitNum\"\r\n");
      out.write("\t\t\t\t\t\tname=\"laboratorySitNum\" class=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">实验室状态</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"laboratoryStatus\"\r\n");
      out.write("\t\t\t\t\t\tname=\"laboratoryStatus\" class=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- \t<tr>\r\n");
      out.write("\t\t\t\t\t关联其他类型修改时设置为树\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">实验室项目</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"experimentalProjectsId\"\r\n");
      out.write("\t\t\t\t\t\tname=\"experimentalProjects\" class=\"easyui-combotree\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"url:'/laboratoryweb/getAllExperimentalProject',multiple:true,required:true,panelHeight:233\" /></td>\r\n");
      out.write("\t\t\t\t</tr> -->\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#laboratorytable\").datagrid({\r\n");
      out.write("\t\t\t\ttitle : \"实验室信息表\",\r\n");
      out.write("\t\t\t\turl : \"/laboratoryweb/getPagerLaboratorys\",\r\n");
      out.write("\t\t\t\tpagination : true,\r\n");
      out.write("\t\t\t\tpageList : [ 10, 20 ],\r\n");
      out.write("\t\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\t\tfield : \"ck\",\r\n");
      out.write("\t\t\t\t\tcheckbox : \"true\"\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"id\",\r\n");
      out.write("\t\t\t\t\tsortable : true,\r\n");
      out.write("\t\t\t\t\ttitle : \"序号\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\tfield : \"laboratoryId\",\r\n");
      out.write("\t\t\t\t\tsortable : true,\r\n");
      out.write("\t\t\t\t\ttitle : \"实验室编号\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"laboratoryName\",\r\n");
      out.write("\t\t\t\t\ttitle : \"实验室名字\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"laboratorySitNum\",\r\n");
      out.write("\t\t\t\t\ttitle : \"实验室座位数量\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t},  {\r\n");
      out.write("\t\t\t\t\tfield : \"laboratoryStatus\",\r\n");
      out.write("\t\t\t\t\ttitle : \"实验室状态\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t},]],\r\n");
      out.write("\t\t\t\t// 背景色交替\r\n");
      out.write("\t\t\t\tstriped : true,\r\n");
      out.write("\t\t\t\t// 增加工具栏\r\n");
      out.write("\t\t\t\ttoolbar : \"#laboratory_tb\",\r\n");
      out.write("\t\t\t\t//行索引传入   使用自带的编辑器\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//保存修改id\r\n");
      out.write("\t\t\t$(\"#searcherbutton\")\r\n");
      out.write("\t\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar laboratoryName = $(\"#searcher_laboratoryName\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.textbox(\"getValue\");\r\n");
      out.write("\t\t\t\t\t\t\t\t//绑定到laboratorytable上\r\n");
      out.write("\t\t\t\t\t\t\t\tvar queryParam = $(\"#laboratorytable\").datagrid(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"options\").queryParams;\r\n");
      out.write("\t\t\t\t\t\t\t\tqueryParam.laboratoryName = laboratoryName;\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#laboratorytable\").datagrid(\"load\");\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t//保存修改\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//新增一条数据\r\n");
      out.write("function addLaboratory() {\r\n");
      out.write("\t\t\t$(\"#laboratory_dialog_form\").form(\"clear\");\r\n");
      out.write("\t\t\t$(\"#laboratorys_dialog\").dialog({\r\n");
      out.write("\t\t\t\ttitle:\"增加用户\",\r\n");
      out.write("\t\t\t\tclosed:false,\r\n");
      out.write("\t\t\t\tmodal:true,\r\n");
      out.write("\t\t\t\tonOpen:function(){\r\n");
      out.write("\t\t\t\t\t$(\"#laboratoryName\").textbox({disabled:false});\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tbuttons:[ //按钮\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttext:\"确定\",\r\n");
      out.write("\t\t\t\t\ticonCls:\"icon-ok\",\r\n");
      out.write("\t\t\t\t\thandler: laboratory_add\r\n");
      out.write("\t\t\t\t    },\r\n");
      out.write("\t\t\t\t    {     text:'取消',iconCls:\"icon-cancel\",\r\n");
      out.write("\t\t\t\t\t    handler:function(){\r\n");
      out.write("\t\t\t\t\t\t$(\"#laboratorys_dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t       \t}\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t       ]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\tfunction updateLaboratory(){\r\n");
      out.write("\t\t\t$(\"#laboratory_dialog_form\").form(\"clear\");\r\n");
      out.write("\t\t\tvar rows = $(\"#laboratorytable\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t\tif(rows.length!=1){\t\t\r\n");
      out.write("\t\t\t\t$.messager.alert(\"提示\",\"请选择一条信息\",\"info\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tvar laboratory = rows[0];\r\n");
      out.write("\t\t\t\t//表单绑定数据\r\n");
      out.write("\t\t\t\t$(\"#laboratory_dialog_form\").form(\"load\",laboratory);\r\n");
      out.write("\t\t\t\t$(\"#laboratorys_dialog\").dialog({\r\n");
      out.write("\t\t\t\t\ttitle:\"修改实验室信息\",\r\n");
      out.write("\t\t\t\t\tclosed:false,\r\n");
      out.write("\t\t\t\t\tmodal:true,\r\n");
      out.write("\t\t\t\t\t//不可修改\r\n");
      out.write("/* \t\t\t\t\tonOpen:function(){\r\n");
      out.write("\t\t\t\t\t\t$(\"#laboratoryName\").textbox({disabled:true});\r\n");
      out.write("\t\t\t\t\t}, */\r\n");
      out.write("\t\t\t\t\tbuttons:[ //按钮\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttext:\"确定\",\r\n");
      out.write("\t\t\t\t\t\ticonCls:\"icon-ok\",\r\n");
      out.write("\t\t\t\t\t\thandler:laboratory_update\r\n");
      out.write("\t\t\t\t\t    },\r\n");
      out.write("\t\t\t\t\t    {     text:'取消',iconCls:\"icon-cancel\",\r\n");
      out.write("\t\t\t\t\t\t    handler:function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#laboratorys_dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t       \t}\r\n");
      out.write("\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t       ]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction laboratory_add(){\r\n");
      out.write("\t\t\tdoAjax(\"/laboratoryweb/addLaboratory\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction laboratory_update(){\r\n");
      out.write("\t\t\tdoAjax(\"/laboratoryweb/updateLaboratory\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction doAjax(param){\r\n");
      out.write("\t\t\t/* var experProjectsId = $(\"#experimentalProjectsId\").val().split(\",\");\r\n");
      out.write("\t\t\tvar experProjectString =\"[\";\r\n");
      out.write("\t\t\tfor(var i = 0;i<experProjectsId.length;i++){\r\n");
      out.write("\t\t\t\texperProjectString += \"{id:\"+experProjectsId[i]+\"},\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\texperProjectString=experProjectString.substring(0,experProjectString.length-1)+\"]\";\r\n");
      out.write("\t        var experProjectajax = eval(\"(\"+experProjectString+\")\"); */\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:param,\r\n");
      out.write("\t\t\t\tmethod:\"post\",\r\n");
      out.write("\t\t\t\tcontentType : \"application/json;charset=utf-8\",\r\n");
      out.write("\t\t\t\tdata:JSON.stringify({\r\n");
      out.write("\t\t\t\t\t//通过id获取值\r\n");
      out.write("\t\t\t\t\tid:$(\"#id\").val(),\r\n");
      out.write("\t\t\t\t\tlaboratoryName:$(\"#laboratoryName\").val(),\r\n");
      out.write("\t\t\t\t\tlaboratoryId:$(\"#laboratoryId\").val(),\r\n");
      out.write("\t\t\t\t\tlaboratorySitNum:$(\"#laboratorySitNum\").val(),\r\n");
      out.write("\t\t\t\t\tlaboratoryStatus:$(\"#laboratoryStatus\").val(),\r\n");
      out.write("/* \t\t\t\t\texperimentalProjects:experProjectajax */\r\n");
      out.write("\t\t\t\t}),\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#laboratorys_dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#laboratorytable\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\talert(\"ok!\");\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\talert(\"请重试！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction deleteLaboratory(){\r\n");
      out.write("\t\t\t\t\tvar rows = $(\"#laboratorytable\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t\t\t\tif(rows.length>=1){\t\r\n");
      out.write("\t\t\t$.messager.confirm(\"提示\",\"确定删除?\",function(result){\r\n");
      out.write("\t\t\t\tif(result){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//定义数组\r\n");
      out.write("\t\t\t\t\tvar ids=[];\r\n");
      out.write("\t\t\t\t\t//遍历rows\r\n");
      out.write("\t\t\t\t\t$(rows).each(function(){\r\n");
      out.write("\t\t\t\t\t\tids.push(this.id);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t//传递ids\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl:\"/laboratoryweb/deleteLaboratory\",\r\n");
      out.write("\t\t\t\t\t\tdata:{ids:ids},\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#laboratorys_dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#laboratorytable\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"ok!\");\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"删除失败！\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"提示\",\"请至少选择一个用户！\",\"info\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction cancel(){\r\n");
      out.write("\t\t\t$(\"#laboratorytable\").datagrid(\"rejectChanges\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
