/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-07 09:42:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class my_002dorder_002dinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"myordr-table\" style=\"width: 100%; height: 100%;\"  />\r\n");
      out.write("\t<div id=\"myordr-tb\">\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" data-options=\"iconCls:'icon-add'\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"deleteOrder()\">选中撤销</a> &nbsp;\r\n");
      out.write("\t\t<div id=\"myordr-dim-search\" class=\"easyui-textbox\"></div>\r\n");
      out.write("\t\t&nbsp; <a href=\"javascript:void(0);\" data-options=\"iconCls:'icon-search'\"\r\n");
      out.write("\t\t\tid=\"myordr-search-btn\" class=\"easyui-linkbutton\">搜索</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#myordr-table\").datagrid({\r\n");
      out.write("\t\t\t\ttitle : \"我的预约信息表\",\r\n");
      out.write("\t\t\t\turl : \"/laboratoryweb/getPagerOrderByUser\",\r\n");
      out.write("\t\t\t\tpagination : true,\r\n");
      out.write("\t\t\t\tstriped : true,\r\n");
      out.write("\t\t\t\tpageSize : 15,\r\n");
      out.write("\t\t\t\tpageList : [ 15, 50, 100 ],\r\n");
      out.write("\t\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\t\tfield : \"orderPKID\",\r\n");
      out.write("\t\t\t\t\thidden : true,\r\n");
      out.write("\t\t\t\t\ttitle : \"orderPKID\",\r\n");
      out.write("\t\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t\tvar role = $(\"#userRole\").val();\r\n");
      out.write("\t\t\t\t\t\tif(role == \"学生\"){\r\n");
      out.write("\t\t\t\t\t\t$('#myordr-table').datagrid('hideColumn', \"stuClass\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"roomId\",\r\n");
      out.write("\t\t\t\t\ttitle : \"实验室\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"roomName\",\r\n");
      out.write("\t\t\t\t\ttitle : \"实验室\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\tfield : \"roomSitId\",\r\n");
      out.write("\t\t\t\t\ttitle : \"座位号\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\tfield : \"orderTime\",\r\n");
      out.write("\t\t\t\t\ttitle : \"预约时间\",\r\n");
      out.write("\t\t\t\t\twidth : 150\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"startTime\",\r\n");
      out.write("\t\t\t\t\ttitle : \"开始时间\",\r\n");
      out.write("\t\t\t\t\twidth : 150\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"endTime\",\r\n");
      out.write("\t\t\t\t\ttitle : \"结束时间\",\r\n");
      out.write("\t\t\t\t\twidth : 150\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"stuClass\",\r\n");
      out.write("\t\t\t\t\ttitle : \"预约班级\",\r\n");
      out.write("\t\t\t\t\twidth : 150,\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"experProjectAccount\",\r\n");
      out.write("\t\t\t\t\ttitle : \"实验项目\",\r\n");
      out.write("\t\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\tif(value == null){\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\treturn \"个人预约\";\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\treturn value;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"status\",\r\n");
      out.write("\t\t\t\t\ttitle : \"当前状态\",\r\n");
      out.write("\t\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t\tif (value == 1) {\r\n");
      out.write("\t\t\t\t\t\t\treturn \"已通过\";\r\n");
      out.write("\t\t\t\t\t\t} else if (value == 0) {\r\n");
      out.write("\t\t\t\t\t\t\treturn \"未审核\";\r\n");
      out.write("\t\t\t\t\t\t} else if (value == 3) {\r\n");
      out.write("\t\t\t\t\t\t\treturn \"已撤销\";\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\treturn \"未通过\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tstyler : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t\tif (value == 1) {\r\n");
      out.write("\t\t\t\t\t\t\treturn 'background-color:#70D41F;color:white;';\r\n");
      out.write("\t\t\t\t\t\t} else if (value == 0) {\r\n");
      out.write("\t\t\t\t\t\t\treturn 'background-color:#FECB41;color:white;';\r\n");
      out.write("\t\t\t\t\t\t} else if (value == 3) {\r\n");
      out.write("\t\t\t\t\t\t\treturn 'background-color:#D9D9D9;color:white;';\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\treturn 'background-color:#E22018;color:white;';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} ] ],\r\n");
      out.write("\t\t\t\tsingleSelect : true,\r\n");
      out.write("\t\t\t\tstriped : true,\r\n");
      out.write("\t\t\t\ttoolbar : \"#myordr-tb\",\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tvar editIndex;\r\n");
      out.write("\t\t\t$(\"#myordr-search-btn\")\r\n");
      out.write("\t\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dimWord = $(\"#myordr-dim-search\").textbox(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"getValue\");\r\n");
      out.write("\t\t\t\t\t\t\t\tvar queryParam = $(\"#myordr-table\").datagrid(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"options\").queryParams;\r\n");
      out.write("\t\t\t\t\t\t\t\tqueryParam.dimWord = dimWord;\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#myordr-table\").datagrid(\"load\");\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction deleteOrder() {\r\n");
      out.write("\t\t\tvar rows = $(\"#myordr-table\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t\tif (rows.length < 1) {\r\n");
      out.write("\t\t\t\t$.messager.alert(\"提示\", \"请至少选择一条信息\", \"info\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tvar laboratory = rows[0];\r\n");
      out.write("\t\t\t\tif (laboratory.status == 0) {\r\n");
      out.write("\t\t\t\t\t$.messager.confirm(\"提示\", \"确定撤销选中预约申请?\", function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result) {\r\n");
      out.write("\t\t\t\t\t\t\tvar ids = [];\r\n");
      out.write("\t\t\t\t\t\t\t$(rows).each(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tids.push(this.orderPKID);\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t//传递ids\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"/laboratoryweb/cancelOrder\",\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tids : ids\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (data == \"success\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#myordr-table\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tAlert(\"撤销申请成功!\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tAlert(\"撤销申请失败！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tAlert(\"仅未通过的预约可撤销!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
