/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-16 06:07:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class a_002dtatistics_002dinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"stat-table\" style=\"width: 100%;height:100%;\" />\r\n");
      out.write("\t<div id=\"stat-tb\">\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp; <select onchange=\"statSelectTable()\"\r\n");
      out.write("\t\t\tstyle=\"height: 25px;\" id=\"statSelectTable\">\r\n");
      out.write("\t\t\t<option value=\"1\">实验室人时数</option>\r\n");
      out.write("\t\t\t<option value=\"2\">教师人时数</option>\r\n");
      out.write("\t\t\t<option value=\"3\">学生人时数</option>\r\n");
      out.write("\t\t</select> &nbsp;&nbsp;&nbsp; 查询日期:\r\n");
      out.write("\t\t<div id=\"statSearcherdate\" class=\"easyui-datebox\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t&nbsp; 查询时间段: <input type=\"text\" id=\"statSearcherTimesection\"\r\n");
      out.write("\t\t\tname=\"orderTimeSection\" class=\"easyui-combotree\"\r\n");
      out.write("\t\t\tdata-options=\"url:'/laboratoryweb/getAllTimeSection',multiple:false,panelHeight:233\" />&nbsp;\r\n");
      out.write("\r\n");
      out.write("\t\t<span style=\"display: none;\" id=\"statStudentIdbox\"> 学生学号:\r\n");
      out.write("\t\t\t<div id=\"statStudentId\" class=\"easyui-numberbox\"></div>&nbsp;\r\n");
      out.write("\t\t</span> <span style=\"display: none;\" id=\"statTeacherIdbox\"> 教师工号:\r\n");
      out.write("\t\t\t<div id=\"statTeacherId\" class=\"easyui-numberbox\"\r\n");
      out.write("\t\t\t\tstyle=\"display: none;\"></div>&nbsp;\r\n");
      out.write("\t\t</span>  <a href=\"javascript:void(0);\" data-options=\"iconCls:'icon-search'\"\r\n");
      out.write("\t\t\tonclick=\"statSearcher()\" id=\"stat-search-btn\" class=\"easyui-linkbutton\">搜索</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$('#statSearcherdate').datebox('setValue', '-');\r\n");
      out.write("\t\t\t$(\"#stat-table\").datagrid({\r\n");
      out.write("\t\t\t\ttitle : \"实验室统计信息查看\",\r\n");
      out.write("\t\t\t\tpagination : true,\r\n");
      out.write("\t\t\t\tpageSize : 13,\r\n");
      out.write("\t\t\t\tpageList : [ 13, 50, 100 ],\r\n");
      out.write("\t\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\t\tfield : \"date\",\r\n");
      out.write("\t\t\t\t\ttitle : \"日期\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"timesection\",\r\n");
      out.write("\t\t\t\t\ttitle : \"时间段\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"laboratoryName\",\r\n");
      out.write("\t\t\t\t\ttitle : \"实验室名字\",\r\n");
      out.write("\t\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"laboratoryId\",\r\n");
      out.write("\t\t\t\t\ttitle : \"实验室编号\",\r\n");
      out.write("\t\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"teacherName\",\r\n");
      out.write("\t\t\t\t\ttitle : \"教师姓名\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"teacherAccount\",\r\n");
      out.write("\t\t\t\t\ttitle : \"教师工号\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"studentName\",\r\n");
      out.write("\t\t\t\t\ttitle : \"学生姓名\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"studentAccount\",\r\n");
      out.write("\t\t\t\t\ttitle : \"学号\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"statisticnum\",\r\n");
      out.write("\t\t\t\t\ttitle : \"人时数\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t} ] ],\r\n");
      out.write("\t\t\t\tstriped : true,\r\n");
      out.write("\t\t\t\ttoolbar : \"#stat-tb\",\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#stat-table').datagrid({\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tonDblClickCell : function(index, field, value) {\r\n");
      out.write("\t\t\t\t\t$(this).datagrid('beginEdit', index);\r\n");
      out.write("\t\t\t\t\tvar ed = $(this).datagrid('getEditor', {\r\n");
      out.write("\t\t\t\t\t\tindex : index,\r\n");
      out.write("\t\t\t\t\t\tfield : field\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t$(ed.target).focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction statSearcher() {\r\n");
      out.write("\t\t\tvar id = $(\"#statSelectTable\").val();\r\n");
      out.write("\t\t\tvar date = $(\"#statSearcherdate\").val();\r\n");
      out.write("\t\t\tvar timesectionId = $(\"#statSearcherTimesection\").val();\r\n");
      out.write("\t\t\tif (date == \"\") {\r\n");
      out.write("\t\t\t\tAlert(\"请选择日期!\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (timesectionId == \"\") {\r\n");
      out.write("\t\t\t\tAlert(\"请选择时间段!\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//动态的添加查询所需的账号(学生、老师、实验室)，以及数据地址\r\n");
      out.write("\t\t\tvar account;\r\n");
      out.write("\t\t\tvar url = \"/laboratoryweb/searchStatistic\";\r\n");
      out.write("\t\t\tif (id == 1) {\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('showColumn', \"laboratoryName\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('showColumn', \"laboratoryId\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('hideColumn', \"teacherName\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('hideColumn', \"teacherAccount\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('hideColumn', \"studentName\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('hideColumn', \"studentAccount\");\r\n");
      out.write("\t\t\t\taccount = $(\"#statLaboratoryId\").val();\r\n");
      out.write("\t\t\t} else if (id == 2) {\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('showColumn', \"teacherName\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('showColumn', \"teacherAccount\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('hideColumn', \"laboratoryName\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('hideColumn', \"laboratoryId\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('hideColumn', \"studentName\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('hideColumn', \"studentAccount\");\r\n");
      out.write("\t\t\t\taccount = $(\"#statTeacherId\").val();\r\n");
      out.write("\t\t\t} else if (id == 3) {\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('showColumn', \"studentName\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('showColumn', \"studentAccount\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('hideColumn', \"laboratoryName\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('hideColumn', \"laboratoryId\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('hideColumn', \"teacherName\");\r\n");
      out.write("\t\t\t\t$('#stat-table').datagrid('hideColumn', \"teacherAccount\");\r\n");
      out.write("\t\t\t\taccount = $(\"#statStudentId\").val();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#stat-table\").datagrid('options').url = url + \"?id=\" + id\r\n");
      out.write("\t\t\t\t\t+ \"&&date=\" + date + \"&&timesectionId=\" + timesectionId\r\n");
      out.write("\t\t\t\t\t+ \"&&Account=\" + account;\r\n");
      out.write("\t\t\t$('#stat-table').datagrid('load');\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction statSelectTable(data) {\r\n");
      out.write("\t\t\tvar id = $(\"#statSelectTable\").val();\r\n");
      out.write("\t\t\tif (id == 1) {\r\n");
      out.write("\t\t\t\t$(\"#statLaboratoryIdbox\").css(\"display\", \"\");\r\n");
      out.write("\t\t\t\t$(\"#statTeacherIdbox\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t\t$(\"#statStudentIdbox\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t} else if (id == 2) {\r\n");
      out.write("\t\t\t\t$(\"#statLaboratoryIdbox\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t\t$(\"#statTeacherIdbox\").css(\"display\", \"\");\r\n");
      out.write("\t\t\t\t$(\"#statStudentIdbox\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t} else if (id == 3) {\r\n");
      out.write("\t\t\t\t$(\"#statLaboratoryIdbox\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t\t$(\"#statTeacherIdbox\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t\t$(\"#statStudentIdbox\").css(\"display\", \"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
