/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-21 12:52:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class experProject_002dmanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"exper-table\" style=\"width: 100%; height: 100%;\" />\r\n");
      out.write("\t<div id=\"exper-tb\">\r\n");
      out.write("\t\t<div class=\"experProjectsToolbar_button\"></div>\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" data-options=\"iconCls:'icon-add'\"\r\n");
      out.write("\t\t\tid=\"addbutton\" class=\"easyui-linkbutton\" onclick=\"addExperProject()\">添加</a>\r\n");
      out.write("\t\t&nbsp; <a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\tdata-options=\"iconCls:'icon-save'\" id=\"updatebutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"updateExperProject()\">修改</a>&nbsp;\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" data-options=\"iconCls:'icon-remove'\"\r\n");
      out.write("\t\t\tid=\"removebutton\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\tonclick=\"deleteExperProject()\">删除</a> &nbsp; <a\r\n");
      out.write("\t\t\thref=\"javascript:void(0);\" data-options=\"iconCls:'icon-cancel'\"\r\n");
      out.write("\t\t\tid=\"cancelbutton\" class=\"easyui-linkbutton\" onclick=\"cancelE()\">取消选择</a>\r\n");
      out.write("\t\t&nbsp; <a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\tdata-options=\"iconCls:'icon-undo'\" id=\"refreshbutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"refreshTable()\">刷新</a> &nbsp;实验室名:\r\n");
      out.write("\t\t<div id=\"seacher_experProjectName\" class=\"easyui-textbox\"></div>\r\n");
      out.write("\t\t&nbsp; <a href=\"#\" data-options=\"iconCls:'icon-search'\"\r\n");
      out.write("\t\t\tplaceholder=\"密码\" id=\"exper-search-btn\" class=\"easyui-linkbutton\">搜索</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 增加的提示框 -->\r\n");
      out.write("\t<div id=\"exper-dialog\" class=\"easyui-dialog\"\r\n");
      out.write("\t\tdata-options=\"closed:true,iconCls:'icon-save'\"\r\n");
      out.write("\t\tstyle=\"width: 400px; height: 300px; padding: 10px;\">\r\n");
      out.write("\t\t<form id=\"exper-dialog-form\" method=\"post\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"100px\" align=\"right\">实验项目名:<input\r\n");
      out.write("\t\t\t\t\t\tid=\"experProjectPKID\" name=\"experProjectPKID\" type=\"hidden\" /></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"experimentalProjectName\"\r\n");
      out.write("\t\t\t\t\t\tname=\"experimentalProjectName\" class=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">实验项目编号:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"experimentalProjectId\"\r\n");
      out.write("\t\t\t\t\t\tname=\"experimentalProjectId\" class=\"easyui-numberbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<!-- 关联其他类型修改时设置为树 -->\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">项目实验室:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"exper-laboratoryId\"\r\n");
      out.write("\t\t\t\t\t\tname=\"laboratory\" class=\"easyui-combotree\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"url:'/laboratoryweb/getAllLaboratory',multiple:false,panelHeight:233\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#exper-table\").datagrid({\r\n");
      out.write("\t\t\t\ttitle : \"项目信息表\",\r\n");
      out.write("\t\t\t\turl : \"/laboratoryweb/getPagerExperProjects\",\r\n");
      out.write("\t\t\t\tpagination : true,\r\n");
      out.write("\t\t\t\tpageSize : 15,\r\n");
      out.write("\t\t\t\tpageList : [ 15, 50, 100 ],\r\n");
      out.write("\t\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\t\tfield : \"ck\",\r\n");
      out.write("\t\t\t\t\tcheckbox : \"true\"\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"experProjectPKID\",\r\n");
      out.write("\t\t\t\t\thidden : true,\r\n");
      out.write("\t\t\t\t\ttitle : \"experProjectPKID\"\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"laboratory\",\r\n");
      out.write("\t\t\t\t\ttitle : \"实验室\",\r\n");
      out.write("\t\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t\treturn value.laboratoryName;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"experimentalProjectId\",\r\n");
      out.write("\t\t\t\t\ttitle : \"实验室编号\",\r\n");
      out.write("\t\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"hasVideo\",\r\n");
      out.write("\t\t\t\t\ttitle : \"是否有材料\",\r\n");
      out.write("\t\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t   if(value==true){\r\n");
      out.write("\t\t\t\t\t\t   return \"有\";\r\n");
      out.write("\t\t\t\t\t   }else{\r\n");
      out.write("\t\t\t\t\t\t   return \"无\";\r\n");
      out.write("\t\t\t\t\t   }\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"experimentalProjectName\",\r\n");
      out.write("\t\t\t\t\ttitle : \"项目名字\",\r\n");
      out.write("\t\t\t\t\twidth : 180\r\n");
      out.write("\t\t\t\t}, ] ],\r\n");
      out.write("\t\t\t\t// 背景色交替\r\n");
      out.write("\t\t\t\tstriped : true,\r\n");
      out.write("\t\t\t\t// 增加工具栏\r\n");
      out.write("\t\t\t\ttoolbar : \"#exper-tb\",\r\n");
      out.write("\t\t\t//行索引传入   使用自带的编辑器\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//保存修改id\r\n");
      out.write("\t\t\tvar editIndex;\r\n");
      out.write("\t\t\t$(\"#exper-search-btn\")\r\n");
      out.write("\t\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar experProjectName = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"#seacher_experProjectName\").textbox(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"getValue\");\r\n");
      out.write("\t\t\t\t\t\t\t\t//绑定到exper-table上\r\n");
      out.write("\t\t\t\t\t\t\t\tvar queryParam = $(\"#exper-table\").datagrid(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"options\").queryParams;\r\n");
      out.write("\t\t\t\t\t\t\t\tqueryParam.experProjectName = experProjectName;\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#exper-table\").datagrid(\"load\");\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t//保存修改\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//新增一条数据\r\n");
      out.write("\t\tfunction addExperProject() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#exper-dialog-form\").form(\"clear\");\r\n");
      out.write("\t\t\t$(\"#exper-dialog\").dialog({\r\n");
      out.write("\t\t\t\ttitle : \"新增项目\",\r\n");
      out.write("\t\t\t\tclosed : false,\r\n");
      out.write("\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\tbuttons : [ //按钮\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttext : \"确定\",\r\n");
      out.write("\t\t\t\t\ticonCls : \"icon-ok\",\r\n");
      out.write("\t\t\t\t\thandler : experProject_add\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\ttext : '取消',\r\n");
      out.write("\t\t\t\t\ticonCls : \"icon-cancel\",\r\n");
      out.write("\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t$(\"#exper-dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction updateExperProject() {\r\n");
      out.write("\t\t\t$(\"#exper-dialog-form\").form(\"clear\");\r\n");
      out.write("\t\t\tvar rows = $(\"#exper-table\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t\tif (rows.length != 1) {\r\n");
      out.write("\t\t\t\t$.messager.alert(\"提示\", \"请选择一条信息\", \"info\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tvar experProject = rows[0];\r\n");
      out.write("\t\t\t\texperProject.laboratory = {\r\n");
      out.write("\t\t\t\t\t\"id\" : experProject.laboratory.laboratoryPKID,\r\n");
      out.write("\t\t\t\t\t\"text\" : experProject.laboratory.laboratoryName\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//表单绑定数据\r\n");
      out.write("\t\t\t\t$(\"#exper-dialog-form\").form(\"load\", experProject);\r\n");
      out.write("\t\t\t\t$(\"#exper-dialog\").dialog({\r\n");
      out.write("\t\t\t\t\ttitle : \"修改项目信息\",\r\n");
      out.write("\t\t\t\t\tclosed : false,\r\n");
      out.write("\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\t//不可修改\r\n");
      out.write("\t\t\t\t\t/* \t\t\t\t\tonOpen:function(){\r\n");
      out.write("\t\t\t\t\t $(\"#experProjectName\").textbox({disabled:true});\r\n");
      out.write("\t\t\t\t\t }, */\r\n");
      out.write("\t\t\t\t\tbuttons : [ //按钮\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttext : \"确定\",\r\n");
      out.write("\t\t\t\t\t\ticonCls : \"icon-ok\",\r\n");
      out.write("\t\t\t\t\t\thandler : experProject_update\r\n");
      out.write("\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\ttext : '取消',\r\n");
      out.write("\t\t\t\t\t\ticonCls : \"icon-cancel\",\r\n");
      out.write("\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#exper-dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction experProject_add() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tdoAjaxE(\"/laboratoryweb/addExperProject\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction experProject_update() {\r\n");
      out.write("\t\t\tdoAjaxE(\"/laboratoryweb/updateExperProject\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction doAjaxE(param) {\r\n");
      out.write("\t\t\tvar data = {\r\n");
      out.write("\t\t\t\t\"id\" : $(\"#experProjectPKID\").val(),\r\n");
      out.write("\t\t\t\t\"experId\" : $(\"#experimentalProjectId\").val(),\r\n");
      out.write("\t\t\t\t\"experProjectName\" : $(\"#experimentalProjectName\").val(),\r\n");
      out.write("\t\t\t\t\"laboratoryId\" : $(\"#exper-laboratoryId\").val()\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\turl : param,\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdata : data,\r\n");
      out.write("\t\t\t\tsuccess : function(mesa) {\r\n");
      out.write("\t\t\t\t\tif (mesa == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#exper-dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#exper-table\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\tAlert(\"操作成功!\");\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tAlert(\"请重试！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction deleteExperProject() {\r\n");
      out.write("\t\t\tvar rows = $(\"#exper-table\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t\tif (rows.length >= 1) {\r\n");
      out.write("\t\t\t\t$.messager.confirm(\"提示\", \"确定删除?\", function(result) {\r\n");
      out.write("\t\t\t\t\tif (result) {\r\n");
      out.write("\t\t\t\t\t\tvar ids = [];\r\n");
      out.write("\t\t\t\t\t\t//遍历rows\r\n");
      out.write("\t\t\t\t\t\t$(rows).each(function() {\r\n");
      out.write("\t\t\t\t\t\t\tids.push(this.experProjectPKID);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t//传递ids\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : \"/laboratoryweb/deleteExperProject\",\r\n");
      out.write("\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\tids : ids\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#exper-dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#exper-table\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAlert(\"删除成功\");\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAlert(\"删除失败！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$.messager.alert(\"提示\", \"请至少选择一条记录！\", \"info\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction cancelE() {\r\n");
      out.write("\t\t\t$(\"#exper-table\").datagrid(\"rejectChanges\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
