/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-16 05:37:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class student_002dmanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"student-table\" style=\"width: 100%; height: 100%;\" />\r\n");
      out.write("\t<div id=\"student-tb\">\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" data-options=\"iconCls:'icon-add'\"\r\n");
      out.write("\t\t\tid=\"addbutton\" class=\"easyui-linkbutton\" onclick=\"addStudent()\">添加</a>\r\n");
      out.write("\t\t&nbsp; <a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\tdata-options=\"iconCls:'icon-save'\" id=\"updatebutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"updateStudent()\">修改</a>&nbsp; <a\r\n");
      out.write("\t\t\thref=\"javascript:void(0);\" data-options=\"iconCls:'icon-remove'\"\r\n");
      out.write("\t\t\tid=\"removebutton\" class=\"easyui-linkbutton\" onclick=\"deleteStudent()\">删除</a>\r\n");
      out.write("\t\t&nbsp; <a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\tdata-options=\"iconCls:'icon-cancel'\" id=\"cancelbutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"cancelS()\">取消选择</a> &nbsp; 学号:\r\n");
      out.write("\t\t<div id=\"stu-searchStuAccount\" class=\"easyui-numberbox\"></div>\r\n");
      out.write("\t\t&nbsp;学生名:\r\n");
      out.write("\t\t<div id=\"stu-searchStuName\" class=\"easyui-textbox\"></div>\r\n");
      out.write("\t\t&nbsp;班级：\r\n");
      out.write("\t\t<div id=\"stu-classn\" class=\"easyui-textbox\"></div>\r\n");
      out.write("\t\t&nbsp; <a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\tdata-options=\"iconCls:'icon-search'\" id=\"stu-seacher-btn\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\">查询</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 增加的提示框 -->\r\n");
      out.write("\t<div id=\"update-dialog\" class=\"easyui-dialog\"\r\n");
      out.write("\t\tdata-options=\"closed:true,iconCls:'icon-save'\"\r\n");
      out.write("\t\tstyle=\"width: 300px; height: 540px; padding: 10px;\">\r\n");
      out.write("\t\t<form id=\"update-form\" method=\"post\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">学生名:&nbsp;<input\r\n");
      out.write("\t\t\t\t\t\tid=\"studentPKID\" name=\"studentPKID\" type=\"hidden\" /></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"stu-studentName\" name=\"studentName\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">学&nbsp;号:&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"stu-studentAccount\"\r\n");
      out.write("\t\t\t\t\t\tname=\"studentAccount\" class=\"easyui-numberbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">密&nbsp;码:&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"stu-studentPassword\"\r\n");
      out.write("\t\t\t\t\t\tname=\"studentPassword\" class=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">状&nbsp;态:&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"stu-status\" name=\"status\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-combotree\" data-options=\"panelHeight:99\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">迟到次数:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"stu-lateTime\" name=\"lateTime\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-numberbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">缺席次数:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"stu-absenceTime\" name=\"absenceTime\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-numberbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"90px\" align=\"right\">当前违纪分数:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"stu-violateScore\"\r\n");
      out.write("\t\t\t\t\t\tname=\"violateScore\" class=\"easyui-numberbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">班级编号:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"stu-stuClass\" name=\"stuClass\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-numberbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 增加的提示框 -->\r\n");
      out.write("\t<div id=\"add-dialog\" class=\"easyui-dialog\"\r\n");
      out.write("\t\tdata-options=\"closed:true,iconCls:'icon-save'\"\r\n");
      out.write("\t\tstyle=\"width: 300px; height: 320px; padding: 10px;\">\r\n");
      out.write("\t\t<form id=\"add-form\" method=\"post\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">学生名:&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"add-stu-studentName\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">学&nbsp;号:&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"add-stu-studentAccount\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-numberbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">密&nbsp;码:&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"add-stu-studentPassword\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">班级编号:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"add-stu-stuClass\" name=\"stuClass\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-numberbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$('#stu-status').combotree('loadData', [ {\r\n");
      out.write("\t\t\t\tid : 1,\r\n");
      out.write("\t\t\t\ttext : '正常',\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tid : 2,\r\n");
      out.write("\t\t\t\ttext : '禁用',\r\n");
      out.write("\t\t\t} ,{\r\n");
      out.write("\t\t\t\tid : 3,\r\n");
      out.write("\t\t\t\ttext : '失效',\r\n");
      out.write("\t\t\t} ]);\r\n");
      out.write("\t\t\t$(\"#student-table\").datagrid({\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : \"&nbsp;&nbsp;&nbsp;学生信息表\",//名字\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"/laboratoryweb/getPagerStudents\",//JSON数据源\r\n");
      out.write("\t\t\t\t\t\t\t\tpagination : true,//分页\r\n");
      out.write("\t\t\t\t\t\t\t\tpageSize : 15,//分页大小\r\n");
      out.write("\t\t\t\t\t\t\t\tpageList : [ 15, 50, 100 ],//可选择的分页大小\r\n");
      out.write("\t\t\t\t\t\t\t\tstriped : true,//显示优化\r\n");
      out.write("\t\t\t\t\t\t\t\ttoolbar : \"#student-tb\",//绑定工具栏\r\n");
      out.write("\t\t\t\t\t\t\t\t//循环数据源展示\r\n");
      out.write("\t\t\t\t\t\t\t\tcolumns : [ [{field : \"ck\",checkbox : \"true\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{field : \"studentPKID\",hidden : true,title : \"studentPKID\",},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{field : \"studentAccount\",title : \"学号\",width : 100},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{field : \"studentName\",title : \"名字\",width : 100},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{field : \"stuClassName\",title : \"班级\",width : 200,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tformatter : function(value, row,index) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar var1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t    async : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : \"/laboratoryweb/getStuClassName\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tmethod : \"get\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata : {\"stuClassId\" : row.stuClass},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar1 = data;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn var1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},{field : \"stuClass\",title : \"班级编号\",width : 100},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{field : \"violateScore\",title : \"当前违纪分数\",width : 120},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{field : \"lateTime\",title : \"历史迟到次数\",width : 100,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tformatter : function(value, row,index) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (value == \"0\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treturn \"无\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treturn value + \"次\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}},},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{field : \"absenceTime\",title : \"历史缺席次数\",width : 100,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tformatter : function(value, row,index) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (value == \"0\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treturn \"无\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treturn value + \"次\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}},},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{field : \"status\",title : \"状态\",width : 100,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tformatter : function(value, row,index) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (value == \"2\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treturn \"禁用\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} else if (value == \"1\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treturn \"正常\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treturn \"失效\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyler : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (value == 1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treturn 'tetx-align:center;background-color:#60D41F;color:white;';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treturn 'background-color:#E22018;color:white;';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}}} ] ],});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#stu-seacher-btn\").click(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar studentAccount = $(\"#stu-searchStuAccount\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.numberbox(\"getValue\");\r\n");
      out.write("\t\t\t\t\t\tvar studentName = $(\"#stu-searchStuName\").textbox(\r\n");
      out.write("\t\t\t\t\t\t\t\t\"getValue\");\r\n");
      out.write("\t\t\t\t\t\tvar classn = $(\"#stu-classn\").textbox(\"getValue\");\r\n");
      out.write("\t\t\t\t\t\tvar queryParam = $(\"#student-table\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.datagrid(\"options\").queryParams;\r\n");
      out.write("\t\t\t\t\t\tqueryParam.studentAccount = studentAccount;\r\n");
      out.write("\t\t\t\t\t\tqueryParam.studentName = studentName;\r\n");
      out.write("\t\t\t\t\t\tqueryParam.classn = classn;\r\n");
      out.write("\t\t\t\t\t\t$(\"#student-table\").datagrid(\"load\");\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction addStudent() {\r\n");
      out.write("\t\t\t$(\"#add-form\").form(\"clear\");\r\n");
      out.write("\t\t\t$(\"#add-dialog\").dialog({\r\n");
      out.write("\t\t\t\ttitle : \"增加学生\",\r\n");
      out.write("\t\t\t\tclosed : false,\r\n");
      out.write("\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\tbuttons : [ {\r\n");
      out.write("\t\t\t\t\ttext : \"确定\",\r\n");
      out.write("\t\t\t\t\ticonCls : \"icon-ok\",\r\n");
      out.write("\t\t\t\t\thandler : student_add\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\ttext : '取消',\r\n");
      out.write("\t\t\t\t\ticonCls : \"icon-cancel\",\r\n");
      out.write("\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t$(\"#add-dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction student_add() {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\turl : \"/laboratoryweb/addStudent\",\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tcontentType : \"application/json;charset=utf-8\",\r\n");
      out.write("\t\t\t\tdata : JSON.stringify({\r\n");
      out.write("\t\t\t\t\tstudentName : $(\"#add-stu-studentName\").val(),\r\n");
      out.write("\t\t\t\t\tstudentAccount : $(\"#add-stu-studentAccount\").val(),\r\n");
      out.write("\t\t\t\t\tstudentPassword : $(\"#add-stu-studentPassword\").val(),\r\n");
      out.write("\t\t\t\t\tstuClass : $(\"#add-stu-stuClass\").val(),\r\n");
      out.write("\t\t\t\t}),\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#add-dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#student-table\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\tAlert(\"添加成功\");\r\n");
      out.write("\t\t\t\t\t} else if(data == \"wrongPassword\"){\r\n");
      out.write("\t\t\t\t\t\tAlert(\"密码应为字母加数字6-12位\");\r\n");
      out.write("\t\t\t\t\t} else if(data == \"wrongClass\"){\r\n");
      out.write("\t\t\t\t\t\tAlert(\"找不到该编号的班级\");\r\n");
      out.write("\t\t\t\t\t} else if(data == \"wrongAccount\"){\r\n");
      out.write("\t\t\t\t\t\tAlert(\"学号重复\");\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\tAlert(\"系统异常,请重试\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction updateStudent() {\r\n");
      out.write("\t\t\t$(\"#update-form\").form(\"clear\");\r\n");
      out.write("\t\t\tvar rows = $(\"#student-table\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t\tif (rows.length != 1) {\r\n");
      out.write("\t\t\t\t$.messager.alert(\"提示\", \"请选择一条数据\", \"info\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tvar student = rows[0];\r\n");
      out.write("\t\t\t\tstudent.studentPassword = \"\";\r\n");
      out.write("\t\t\t\t$(\"#update-form\").form(\"load\", student);\r\n");
      out.write("\t\t\t\t$(\"#update-dialog\").dialog({\r\n");
      out.write("\t\t\t\t\ttitle : \"修改用户\",\r\n");
      out.write("\t\t\t\t\tclosed : false,\r\n");
      out.write("\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\tbuttons : [ {\r\n");
      out.write("\t\t\t\t\t\ttext : \"确定\",\r\n");
      out.write("\t\t\t\t\t\ticonCls : \"icon-ok\",\r\n");
      out.write("\t\t\t\t\t\thandler : student_update\r\n");
      out.write("\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\ttext : '取消',\r\n");
      out.write("\t\t\t\t\t\ticonCls : \"icon-cancel\",\r\n");
      out.write("\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#update-dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction student_update() {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\turl : \"/laboratoryweb/updateStudent\",\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tcontentType : \"application/json;charset=utf-8\",\r\n");
      out.write("\t\t\t\tdata : JSON.stringify({\r\n");
      out.write("\t\t\t\t\tstudentPKID : $(\"#studentPKID\").val(),\r\n");
      out.write("\t\t\t\t\tstudentName : $(\"#stu-studentName\").val(),\r\n");
      out.write("\t\t\t\t\tstudentAccount : $(\"#stu-studentAccount\").val(),\r\n");
      out.write("\t\t\t\t\tlateTime : $(\"#stu-lateTime\").val(),\r\n");
      out.write("\t\t\t\t\tabsenceTime : $(\"#stu-absenceTime\").val(),\r\n");
      out.write("\t\t\t\t\tviolateScore : $(\"#stu-violateScore\").val(),\r\n");
      out.write("\t\t\t\t\tstudentPassword : $(\"#stu-studentPassword\").val(),\r\n");
      out.write("\t\t\t\t\tstuClass : $(\"#stu-stuClass\").val(),\r\n");
      out.write("\t\t\t\t\tstatus : $(\"#stu-status\").val(),\r\n");
      out.write("\t\t\t\t}),\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#update-dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#student-table\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\tAlert(\" 修改成功 \");\r\n");
      out.write("\t\t\t\t\t} else if(data == \"wrongPassword\"){\r\n");
      out.write("\t\t\t\t\t\tAlert(\"密码应为字母加数字6-12位\");\r\n");
      out.write("\t\t\t\t\t} else if(data == \"wrongClass\"){\r\n");
      out.write("\t\t\t\t\t\tAlert(\"找不到该编号的班级\");\r\n");
      out.write("\t\t\t\t\t} else if(data == \"nameFalse\"){\r\n");
      out.write("\t\t\t\t\t\tAlert(\"修改名字请输入密码\");\r\n");
      out.write("\t\t\t\t\t}  else{\r\n");
      out.write("\t\t\t\t\t\tAlert(\"系统异常,请重试\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction deleteStudent() {\r\n");
      out.write("\t\t\tvar rows = $(\"#student-table\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t\tif (rows.length >= 1) {\r\n");
      out.write("\t\t\t\t$.messager.confirm(\"提示\", \"确定删除?\", function(result) {\r\n");
      out.write("\t\t\t\t\tif (result) {\r\n");
      out.write("\t\t\t\t\t\tvar ids = [];\r\n");
      out.write("\t\t\t\t\t\t$(rows).each(function() {\r\n");
      out.write("\t\t\t\t\t\t\tids.push(this.studentPKID);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : \"/laboratoryweb/deleteStudent\",\r\n");
      out.write("\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\tids : ids\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#student-table\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAlert(\"删除成功!\");\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAlert(\"删除失败！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$.messager.alert(\"提示\", \"请至少选择一个用户！\", \"info\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction cancelS() {\r\n");
      out.write("\t\t\t$(\"#student-table\").datagrid(\"rejectChanges\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
