/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-25 05:43:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class teacher_002dmanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"teacher-table\" style=\"width: 100%; height: 100%;\" />\r\n");
      out.write("\t<div id=\"teacher-tb\">\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" data-options=\"iconCls:'icon-add'\"\r\n");
      out.write("\t\t\tid=\"addbutton\" class=\"easyui-linkbutton\" onclick=\"addTeacher()\">添加</a>\r\n");
      out.write("\t\t&nbsp; <a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\tdata-options=\"iconCls:'icon-save'\" id=\"updatebutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"updateTeacher()\">修改</a>&nbsp; <a\r\n");
      out.write("\t\t\thref=\"javascript:void(0);\" data-options=\"iconCls:'icon-remove'\"\r\n");
      out.write("\t\t\tid=\"removebutton\" class=\"easyui-linkbutton\" onclick=\"deleteTeacher()\">删除</a>\r\n");
      out.write("\t\t&nbsp; <a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\tdata-options=\"iconCls:'icon-cancel'\" id=\"cancelbutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"cancelT()\">取消选择</a> &nbsp; 账号:\r\n");
      out.write("\t\t<div id=\"searchTeacherAccount\" class=\"easyui-numberbox\"></div>\r\n");
      out.write("\t\t&nbsp;用户名:\r\n");
      out.write("\t\t<div id=\"searchTeacherName\" class=\"easyui-textbox\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t&nbsp;学院: <input type=\"text\" id=\"searchDepartment\"\r\n");
      out.write("\t\t\tname=\"searchDepartment\" class=\"easyui-combotree\"\r\n");
      out.write("\t\t\tdata-options=\"url:'/laboratoryweb/getAllDepartments',multiple:false,panelHeight:203\" />&nbsp;\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" data-options=\"iconCls:'icon-search'\"\r\n");
      out.write("\t\t\tid=\"teacher-search-btn\" class=\"easyui-linkbutton\">查询</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 增加的提示框 -->\r\n");
      out.write("\t<div id=\"teacher-dialog\" class=\"easyui-dialog\"\r\n");
      out.write("\t\tdata-options=\"closed:true,iconCls:'icon-save'\"\r\n");
      out.write("\t\tstyle=\"width: 320px; height: 360px; padding: 10px;\">\r\n");
      out.write("\t\t<form id=\"teacher-dialog-form\" method=\"post\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">教师名 <input id=\"teacherPKID\"\r\n");
      out.write("\t\t\t\t\t\tname=\"teacherPKID\" type=\"hidden\" /></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"t-teacherName\" name=\"teacherName\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">工号</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"t-teacherAccount\"\r\n");
      out.write("\t\t\t\t\t\tname=\"teacherAccount\" class=\"easyui-numberbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">密码</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"t-teacherPassword\"\r\n");
      out.write("\t\t\t\t\t\tname=\"teacherPassword\" class=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">状&nbsp;态:&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"teacher-status\" name=\"status\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-combotree\" data-options=\"panelHeight:99\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"80px\" align=\"right\">所属学院</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"t-department\" name=\"department\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-combotree\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"url:'/laboratoryweb/getAllDepartments',multiple:false,panelHeight:203\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$('#teacher-status').combotree('loadData', [ {\r\n");
      out.write("\t\t\t\tid : 1,\r\n");
      out.write("\t\t\t\ttext : '正常',\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tid : 2,\r\n");
      out.write("\t\t\t\ttext : '禁用',\r\n");
      out.write("\t\t\t} ]);\r\n");
      out.write("\t\t\t$(\"#teacher-table\").datagrid({\r\n");
      out.write("\t\t\t\ttitle : \"&nbsp;&nbsp;&nbsp;&nbsp;教师信息表\",\r\n");
      out.write("\t\t\t\turl : \"/laboratoryweb/getPagerTeachers\",\r\n");
      out.write("\t\t\t\tpagination : true,\r\n");
      out.write("\t\t\t\tpageSize : 15,\r\n");
      out.write("\t\t\t\tpageList : [ 15, 50, 100 ],\r\n");
      out.write("\t\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\t\tfield : \"ck\",\r\n");
      out.write("\t\t\t\t\tcheckbox : \"true\"\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"teacherPKID\",\r\n");
      out.write("\t\t\t\t\thidden : true,\r\n");
      out.write("\t\t\t\t\ttitle : \"teacherPKID\"\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"teacherAccount\",\r\n");
      out.write("\t\t\t\t\ttitle : \"工号\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"teacherName\",\r\n");
      out.write("\t\t\t\t\ttitle : \"名字\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"department\",\r\n");
      out.write("\t\t\t\t\ttitle : \"学院\",\r\n");
      out.write("\t\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t\tvar departmentName;\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\t\t\t\turl : \"/laboratoryweb/getTeacherDepart\",\r\n");
      out.write("\t\t\t\t\t\t\tmethod : \"get\",\r\n");
      out.write("\t\t\t\t\t\t\tdatatype : \"json\",\r\n");
      out.write("\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\"teacherId\" : row.teacherPKID\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\tdepartmentName = data.text;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\treturn departmentName;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\tfield : \"status\",\r\n");
      out.write("\t\t\t\t\ttitle : \"状态\",\r\n");
      out.write("\t\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\t\tformatter : function(value, row,\r\n");
      out.write("\t\t\t\t\t\t\tindex) {\r\n");
      out.write("\t\t\t\t\t\tif (value == \"2\") {\r\n");
      out.write("\t\t\t\t\t\t\treturn \"禁用\";\r\n");
      out.write("\t\t\t\t\t\t} else if (value == \"1\") {\r\n");
      out.write("\t\t\t\t\t\t\treturn \"正常\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tstyler : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t\tif (value == 1) {\r\n");
      out.write("\t\t\t\t\t\t\treturn 'tetx-align:center;background-color:#60D41F;color:white;';\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\treturn 'background-color:#E22018;color:white;';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}  ] ],\r\n");
      out.write("\t\t\t\tstriped : true,\r\n");
      out.write("\t\t\t\ttoolbar : \"#teacher-tb\",\r\n");
      out.write("\t\t\t\tsingleSelect : true\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//保存修改id\r\n");
      out.write("\t\t\tvar editIndex;\r\n");
      out.write("\t\t\t$(\"#teacher-search-btn\").click(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar teacherAccount = $(\"#searchTeacherAccount\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.numberbox(\"getValue\");\r\n");
      out.write("\t\t\t\t\t\tvar teacherName = $(\"#searchTeacherName\").textbox(\r\n");
      out.write("\t\t\t\t\t\t\t\t\"getValue\");\r\n");
      out.write("\t\t\t\t\t\tvar searchDepartment = $(\"#searchDepartment\").textbox(\r\n");
      out.write("\t\t\t\t\t\t\t\t\"getValue\");\r\n");
      out.write("\t\t\t\t\t\tvar queryParam = $(\"#teacher-table\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.datagrid(\"options\").queryParams;\r\n");
      out.write("\t\t\t\t\t\tqueryParam.teacherAccount = teacherAccount;\r\n");
      out.write("\t\t\t\t\t\tqueryParam.teacherName = teacherName;\r\n");
      out.write("\t\t\t\t\t\tqueryParam.searchDepartment = searchDepartment;\r\n");
      out.write("\t\t\t\t\t\t$(\"#teacher-table\").datagrid(\"load\");\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction addTeacher() {\r\n");
      out.write("\t\t\t$(\"#teacher-dialog-form\").form(\"clear\");\r\n");
      out.write("\t\t\t$(\"#teacher-dialog\").dialog({\r\n");
      out.write("\t\t\t\ttitle : \"增加教师用户\",\r\n");
      out.write("\t\t\t\tclosed : false,\r\n");
      out.write("\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\tbuttons : [ //按钮\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttext : \"确定\",\r\n");
      out.write("\t\t\t\t\ticonCls : \"icon-ok\",\r\n");
      out.write("\t\t\t\t\thandler : teacher_add\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\ttext : '取消',\r\n");
      out.write("\t\t\t\t\ticonCls : \"icon-cancel\",\r\n");
      out.write("\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t$(\"#teacher-dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction updateTeacher() {\r\n");
      out.write("\t\t\t$(\"#teacher-dialog-form\").form(\"clear\");\r\n");
      out.write("\t\t\tvar rows = $(\"#teacher-table\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t\tif (rows.length != 1) {\r\n");
      out.write("\t\t\t\t$.messager.alert(\"提示\", \"请选择一条数据\", \"info\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tvar teacher = rows[0];\r\n");
      out.write("\t\t\t\tteacher.teacherPassword = \"\";\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\t\turl : \"/laboratoryweb/getTeacherDepart\",\r\n");
      out.write("\t\t\t\t\tmethod : \"get\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\"teacherId\" : teacher.teacherPKID\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tteacher.department = data;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t//表单绑定数据\r\n");
      out.write("\t\t\t\t$(\"#teacher-dialog-form\").form(\"load\", teacher);\r\n");
      out.write("\t\t\t\t$(\"#teacher-dialog\").dialog({\r\n");
      out.write("\t\t\t\t\ttitle : \"修改教师信息\",\r\n");
      out.write("\t\t\t\t\tclosed : false,\r\n");
      out.write("\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\tbuttons : [ //按钮\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttext : \"确定\",\r\n");
      out.write("\t\t\t\t\t\ticonCls : \"icon-ok\",\r\n");
      out.write("\t\t\t\t\t\thandler : teacher_update\r\n");
      out.write("\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\ttext : '取消',\r\n");
      out.write("\t\t\t\t\t\ticonCls : \"icon-cancel\",\r\n");
      out.write("\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#teacher-dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction teacher_add() {\r\n");
      out.write("\t\t\tdoAjaxT(\"/laboratoryweb/addTeacher\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction teacher_update() {\r\n");
      out.write("\t\t\tdoAjaxT(\"/laboratoryweb/updateTeacher\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction doAjaxT(param) {\r\n");
      out.write("\t\t\tvar departmentId = $(\"#t-department\").val();\r\n");
      out.write("\t\t\tvar teacherName = $(\"#t-teacherName\").val();\r\n");
      out.write("\t\t\tvar teacherAccount = $(\"#t-teacherAccount\").val();\r\n");
      out.write("\t\t\tvar status = $(\"#teacher-status\").val();\r\n");
      out.write("\t\t\tvar id = $(\"#teacherPKID\").val();\r\n");
      out.write("\t\t\tvar teacherPassword = $(\"#t-teacherPassword\").val();\r\n");
      out.write("\t\t\tif (teacherName == \"\") {\r\n");
      out.write("\t\t\t\tAlert(\"请输入姓名\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (teacherAccount == \"\") {\r\n");
      out.write("\t\t\t\tAlert(\"请输入工号\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (departmentId == \"\") {\r\n");
      out.write("\t\t\t\tAlert(\"请选择学院\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (status == \"\") {\r\n");
      out.write("\t\t\t\tstatus = 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : param,\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\tid : id,\r\n");
      out.write("\t\t\t\t\tteacherName : teacherName,\r\n");
      out.write("\t\t\t\t\tteacherAccount : teacherAccount,\r\n");
      out.write("\t\t\t\t\tteacherPassword : teacherPassword,\r\n");
      out.write("\t\t\t\t\tdepartmentId : departmentId,\r\n");
      out.write("\t\t\t\t\tstatus : status\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#teacher-dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#teacher-table\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\tAlert(\"操作成功\");\r\n");
      out.write("\t\t\t\t\t} else if (data == \"wrongPassword\") {\r\n");
      out.write("\t\t\t\t\t\tAlert(\"密码应为字母加数字6-12位\");\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tAlert(\"系统异常,请重试\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction deleteTeacher() {\r\n");
      out.write("\t\t\tvar rows = $(\"#teacher-table\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t\tif (rows.length >= 1) {\r\n");
      out.write("\t\t\t\t$.messager.confirm(\"提示\", \"确定删除?\", function(result) {\r\n");
      out.write("\t\t\t\t\tif (result) {\r\n");
      out.write("\t\t\t\t\t\tvar ids = [];\r\n");
      out.write("\t\t\t\t\t\t$(rows).each(function() {\r\n");
      out.write("\t\t\t\t\t\t\tids.push(this.teacherPKID);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : \"/laboratoryweb/deleteTeacher\",\r\n");
      out.write("\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\tids : ids\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#teacher-dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#teacher-table\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAlert(\"删除成功!\");\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAlert(\"删除失败！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$.messager.alert(\"提示\", \"请至少选择一个用户！\", \"info\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction cancelT() {\r\n");
      out.write("\t\t\t$(\"#teacher-table\").datagrid(\"rejectChanges\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
