/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-03-28 13:17:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_002dmanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"userTable\" style=\"width: 1200px;\" />\r\n");
      out.write("\t<div id=\"userTB\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t&nbsp; 请选择用户类型:&nbsp;&nbsp; <select onchange=\"selectRole()\"\r\n");
      out.write("\t\t\tstyle=\"height: 25px; width: 80px;\" id=\"selectTable\">\r\n");
      out.write("\t\t\t<option value=\"1\">学生</option>\r\n");
      out.write("\t\t\t<option value=\"2\">教师</option>\r\n");
      out.write("\t\t</select>&nbsp; <a href=\"#\" data-options=\"iconCls:'icon-add'\" id=\"addbutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"addUser()\">添加</a> &nbsp; <a\r\n");
      out.write("\t\t\thref=\"#\" data-options=\"iconCls:'icon-save'\" id=\"updatebutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"updateUser()\">修改</a>&nbsp; <a\r\n");
      out.write("\t\t\thref=\"#\" data-options=\"iconCls:'icon-remove'\" id=\"removebutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"deleteUser()\">删除</a> &nbsp; <a\r\n");
      out.write("\t\t\thref=\"#\" data-options=\"iconCls:'icon-cancel'\" id=\"cancelbutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"cancel()\">取消选择</a> &nbsp; <a\r\n");
      out.write("\t\t\thref=\"#\" data-options=\"iconCls:'icon-undo'\" id=\"refreshbutton\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" onclick=\"refreshTable()\">刷新</a> &nbsp; 账号:\r\n");
      out.write("\t\t<div id=\"seacher_account\" class=\"easyui-numberbox\"></div>\r\n");
      out.write("\t\t&nbsp;用户名:\r\n");
      out.write("\t\t<div id=\"seacher_username\" class=\"easyui-textbox\"></div>\r\n");
      out.write("\t\t&nbsp; <a href=\"#\" data-options=\"iconCls:'icon-search'\"\r\n");
      out.write("\t\t\tid=\"seacherbutton\" class=\"easyui-linkbutton\">查询</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 增加的提示框 -->\r\n");
      out.write("\t<div id=\"users_dialog\" class=\"easyui-dialog\"\r\n");
      out.write("\t\tdata-options=\"closed:true,iconCls:'icon-save'\"\r\n");
      out.write("\t\tstyle=\"width: 500px; height: 300px; padding: 10px;\">\r\n");
      out.write("\t\t<form id=\"user_dialog_form\" method=\"post\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">用户名 <input id=\"id\" name=\"id\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"hidden\" /></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"userName\" name=\"userName\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">用户账号</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"userAccount\" name=\"userAccount\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">用户密码</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"userPassword\" name=\"userPassword\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-textbox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">注册日期</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"regDate\" name=\"regDate\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-datebox\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<!-- 关联其他类型修改时设置为树 -->\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" align=\"right\">角色</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"rolesId\" name=\"roles\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-combotree\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"url:'/laboratoryweb/getAllRoles',multiple:true,required:true,panelHeight:133\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#userTable\").datagrid({\r\n");
      out.write("\t\t\t\ttitle : \"&nbsp;&nbsp;&nbsp;&nbsp;用户信息表\",\r\n");
      out.write("\t\t\t\turl : \"/laboratoryweb/getPagerStudents\",\r\n");
      out.write("\t\t\t\tpagination : true,\r\n");
      out.write("\t\t\t\tpageList : [ 10, 20 ],\r\n");
      out.write("\t\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\t\tfield : \"ck\",\r\n");
      out.write("\t\t\t\t\tcheckbox : \"true\"\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"id\",\r\n");
      out.write("\t\t\t\t\tsortable : true,\r\n");
      out.write("\t\t\t\t\ttitle : \"id\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"studentAccount\",\r\n");
      out.write("\t\t\t\t\ttitle : \"学号\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"studentName\",\r\n");
      out.write("\t\t\t\t\ttitle : \"名字\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"status\",\r\n");
      out.write("\t\t\t\t\ttitle : \"状态\",\r\n");
      out.write("\t\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t\tif (value == \"0\") {\r\n");
      out.write("\t\t\t\t\t\t\treturn \"禁用\";\r\n");
      out.write("\t\t\t\t\t\t} else if (value == \"1\") {\r\n");
      out.write("\t\t\t\t\t\t\treturn \"正常\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\tfield : \"stuClass\",\r\n");
      out.write("\t\t\t\t\ttitle : \"班级\",\r\n");
      out.write("\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t}, ] ],\r\n");
      out.write("\t\t\t\t// 背景色交替\r\n");
      out.write("\t\t\t\tstriped : true,\r\n");
      out.write("\t\t\t\t// 增加工具栏\r\n");
      out.write("\t\t\t\ttoolbar : \"#userTB\",\r\n");
      out.write("\t\t\t//行索引传入   使用自带的编辑器\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//保存修改id\r\n");
      out.write("\t\t\tvar editIndex;\r\n");
      out.write("\t\t\t$(\"#seacherbutton\")\r\n");
      out.write("\t\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar userAccount = $(\"#seacher_account\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.numberbox(\"getValue\");\r\n");
      out.write("\t\t\t\t\t\t\t\tvar userName = $(\"#seacher_username\").textbox(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"getValue\");\r\n");
      out.write("\t\t\t\t\t\t\t\tvar queryParam = $(\"#userTable\").datagrid(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"options\").queryParams;\r\n");
      out.write("\t\t\t\t\t\t\t\tqueryParam.userAccount = userAccount;\r\n");
      out.write("\t\t\t\t\t\t\t\tqueryParam.userName = userName;\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#userTable\").datagrid(\"load\");\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t//保存修改\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//新增一条数据\r\n");
      out.write("\t\tfunction addUser() {\r\n");
      out.write("\t\t\t$(\"#user_dialog_form\").form(\"clear\");\r\n");
      out.write("\t\t\t$(\"#users_dialog\").dialog({\r\n");
      out.write("\t\t\t\ttitle : \"增加用户\",\r\n");
      out.write("\t\t\t\tclosed : false,\r\n");
      out.write("\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\tonOpen : function() {\r\n");
      out.write("\t\t\t\t\t$(\"#userName\").textbox({\r\n");
      out.write("\t\t\t\t\t\tdisabled : false\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tbuttons : [ //按钮\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttext : \"确定\",\r\n");
      out.write("\t\t\t\t\ticonCls : \"icon-ok\",\r\n");
      out.write("\t\t\t\t\thandler : user_add\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\ttext : '取消',\r\n");
      out.write("\t\t\t\t\ticonCls : \"icon-cancel\",\r\n");
      out.write("\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t$(\"#users_dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction updateUser() {\r\n");
      out.write("\t\t\t$(\"#user_dialog_form\").form(\"clear\");\r\n");
      out.write("\t\t\tvar rows = $(\"#usertable\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t\tif (rows.length != 1) {\r\n");
      out.write("\t\t\t\t$.messager.alert(\"提示\", \"请选择一条数据\", \"info\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tvar user = rows[0];\r\n");
      out.write("\t\t\t\tuser.userPassword = \"\";\r\n");
      out.write("\t\t\t\t//表单绑定数据\r\n");
      out.write("\t\t\t\t$(\"#user_dialog_form\").form(\"load\", user);\r\n");
      out.write("\t\t\t\t$(\"#users_dialog\").dialog({\r\n");
      out.write("\t\t\t\t\ttitle : \"修改用户\",\r\n");
      out.write("\t\t\t\t\tclosed : false,\r\n");
      out.write("\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\t//不可修改\r\n");
      out.write("\t\t\t\t\tonOpen : function() {\r\n");
      out.write("\t\t\t\t\t\t$(\"#userName\").textbox({\r\n");
      out.write("\t\t\t\t\t\t\tdisabled : true\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tbuttons : [ //按钮\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttext : \"确定\",\r\n");
      out.write("\t\t\t\t\t\ticonCls : \"icon-ok\",\r\n");
      out.write("\t\t\t\t\t\thandler : user_update\r\n");
      out.write("\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\ttext : '取消',\r\n");
      out.write("\t\t\t\t\t\ticonCls : \"icon-cancel\",\r\n");
      out.write("\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#users_dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction user_add() {\r\n");
      out.write("\t\t\tdoAjax(\"/laboratoryweb/addUser\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction user_update() {\r\n");
      out.write("\t\t\tdoAjax(\"/laboratoryweb/updateUser\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction selectRole() {\r\n");
      out.write("\t\t\tvar id = $(\"#selectTable\").val();\r\n");
      out.write("\t\t\tvar url;\r\n");
      out.write("\t\t\tif (id == 1) {\r\n");
      out.write("\t\t\t\turl = \"/laboratoryweb/getPagerStudents\";\r\n");
      out.write("\t\t\t} else if (id == 2) {\r\n");
      out.write("\t\t\t\turl = \"/laboratoryweb/getPagerTeachers\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\"#userTable\").datagrid('options').url = url;\r\n");
      out.write("\t\t\t$('#userTable').datagrid('load');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction doAjax(param) {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : param,\r\n");
      out.write("\t\t\t\tcontentType : \"application/json;charset=utf-8\",\r\n");
      out.write("\t\t\t\tdata : JSON.stringify({\r\n");
      out.write("\t\t\t\t\t//通过id获取值\r\n");
      out.write("\t\t\t\t\tid : $(\"#id\").val(),\r\n");
      out.write("\t\t\t\t\tuserName : $(\"#userName\").val(),\r\n");
      out.write("\t\t\t\t\tuserAccount : $(\"#userAccount\").val(),\r\n");
      out.write("\t\t\t\t\tuserPassword : $(\"#userPassword\").val(),\r\n");
      out.write("\t\t\t\t}),\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#users_dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#usertable\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\talert(\"ok!\");\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\talert(\"修改失败！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction deleteUser() {\r\n");
      out.write("\t\t\tvar rows = $(\"#usertable\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t\tif (rows.length >= 1) {\r\n");
      out.write("\t\t\t\t$.messager.confirm(\"提示\", \"确定删除?\", function(result) {\r\n");
      out.write("\t\t\t\t\tif (result) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t//定义数组\r\n");
      out.write("\t\t\t\t\t\tvar ids = [];\r\n");
      out.write("\t\t\t\t\t\t//遍历rows\r\n");
      out.write("\t\t\t\t\t\t$(rows).each(function() {\r\n");
      out.write("\t\t\t\t\t\t\tids.push(this.id);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t//传递ids\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : \"/laboratoryweb/deleteUser\",\r\n");
      out.write("\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\tids : ids\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#users_dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#usertable\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"ok!\");\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"删除失败！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$.messager.alert(\"提示\", \"请至少选择一个用户！\", \"info\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction cancel() {\r\n");
      out.write("\t\t\t$(\"#userTable\").datagrid(\"rejectChanges\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
