/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-07 14:41:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page.teacher;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class t_002dexperProject_002dmanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"experProjectTable\" style=\"width: 100%; height: 100%;\" />\r\n");
      out.write("\t<div id=\"experProject_tb\">\r\n");
      out.write("\t\t&nbsp;实验室名:\r\n");
      out.write("\t\t<div id=\"seacher_experProjectName\" class=\"easyui-textbox\"></div>\r\n");
      out.write("\t\t&nbsp; <a href=\"#\" data-options=\"iconCls:'icon-search'\"\r\n");
      out.write("\t\t\tid=\"exper-search-btn\" class=\"easyui-linkbutton\">搜索</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 增加的提示框 -->\r\n");
      out.write("\t<div id=\"video_dialog\" class=\"easyui-dialog\"\r\n");
      out.write("\t\tdata-options=\"closed:true,iconCls:'icon-save'\"\r\n");
      out.write("\t\tstyle=\"width: 410px; height: 270px; padding: 10px;\">\r\n");
      out.write("\t\t<form class=\"video_dialog_form\" id=\"video_dialog_form\"\r\n");
      out.write("\t\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"80px\" align=\"right\">项目编号:&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" class=\"file-btn\"\r\n");
      out.write("\t\t\t\t\t\tid=\"experimentalProjectId\" disabled=\"disabled\"\r\n");
      out.write("\t\t\t\t\t\tname=\"experimentalProjectId\" /><input type=\"hidden\" id=\"hasVideo\"\r\n");
      out.write("\t\t\t\t\t\tname=\"hasVideo\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"80px\" align=\"right\">实验视频:&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td><input class=\"file-btn\" type=\"file\" id=\"video\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"80px\" align=\"right\">学习资料:&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td><input class=\"file-btn\" type=\"file\" id=\"learnfile\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#experProjectTable\")\r\n");
      out.write("\t\t\t\t\t.datagrid(\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : \"项目信息表\",\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"/laboratoryweb/getPagerExperProjects\",\r\n");
      out.write("\t\t\t\t\t\t\t\tpagination : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tsingleSelect : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tpageSize : 15,\r\n");
      out.write("\t\t\t\t\t\t\t\tpageList : [ 15, 50, 100 ],\r\n");
      out.write("\t\t\t\t\t\t\t\tcolumns : [ [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"experProjectPKID\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thidden : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"experProjectPKID\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"experimentalProjectId\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsortable : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"编号\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"laboratory\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"实验室\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 180,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tformatter : function(value, row,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tindex) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn value.laboratoryName;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"experimentalProjectName\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"项目名字\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 200\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"hasVideo\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"学习资料\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tformatter : function(value, row,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tindex) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (value == true) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treturn \"有\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treturn \"无\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \" \",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"上传视频\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tformatter : function(value, row,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tindex) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar btn = '<a class=\"uploadvf\" onclick=\"uploadbtn('\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ index\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ')\"  href=\"javascript:void(0);\"></a>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn btn;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"  \",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"视频观看\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 200,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tformatter : function(value, row,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tindex) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar btn = '<a id=\"watchVideoid'+index+'\" class=\"watchVideo\"   onclick=\"tWatchVideo('\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ index\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ')\"  href=\"javascript:void(0);\"></a>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn btn;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"   \",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"资料下载\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 200,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tformatter : function(value, row,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tindex) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar btn = '<a class=\"download\"'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ' href=\"/laboratoryweb/downloadFile?experProjectPKID='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ row.experProjectPKID\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '\"></a>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn btn;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t} ] ],\r\n");
      out.write("\t\t\t\t\t\t\t\tonLoadSuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('.uploadvf').linkbutton({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttext : '上传视频及资料',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplain : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticonCls : 'icon-add'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('.watchVideo').linkbutton({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttext : '观看视频',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplain : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticonCls : 'icon-add'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('.download').linkbutton({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttext : '资料下载',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplain : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticonCls : 'icon-add'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tstriped : true,\r\n");
      out.write("\t\t\t\t\t\t\t\ttoolbar : \"#experProject_tb\",\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t$(\"#exper-search-btn\").click(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar experProjectName = $(\"#seacher_experProjectName\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.textbox(\"getValue\");\r\n");
      out.write("\t\t\t\t\t\tvar queryParam = $(\"#experProjectTable\").datagrid(\r\n");
      out.write("\t\t\t\t\t\t\t\t\"options\").queryParams;\r\n");
      out.write("\t\t\t\t\t\tqueryParam.experProjectName = experProjectName;\r\n");
      out.write("\t\t\t\t\t\t$(\"#experProjectTable\").datagrid(\"load\");\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction uploadbtn(id) {\r\n");
      out.write("\t\t\tvar rows = $(\"#experProjectTable\").datagrid(\"getRows\");\r\n");
      out.write("\t\t\tvar oneRow = rows[id];\r\n");
      out.write("\t\t\tvar experimentalProjectId = oneRow[\"experimentalProjectId\"];\r\n");
      out.write("\t\t\tvar hasVideo = oneRow[\"hasVideo\"];\r\n");
      out.write("\t\t\tif (hasVideo) {\r\n");
      out.write("\t\t\t\t$.messager.confirm(\"提示\", \"该项目已有视频,是否进行覆盖?\", function(result) {\r\n");
      out.write("\t\t\t\t\tif (result) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#video_dialog_form\").form(\"clear\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#video_dialog\").dialog(\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonOpen : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('#experimentalProjectId').val(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\texperimentalProjectId);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('#hasVideo').val(hasVideo);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle : \"资料上传\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclosed : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbuttons : [ //按钮\r\n");
      out.write("\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttext : \"上传\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticonCls : \"icon-ok\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thandler : upload\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttext : '取消',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticonCls : \"icon-cancel\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(\"#video_dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#video_dialog_form\").form(\"clear\");\r\n");
      out.write("\t\t\t\t$(\"#video_dialog\").dialog({\r\n");
      out.write("\t\t\t\t\tonOpen : function() {\r\n");
      out.write("\t\t\t\t\t\t$('#hasVideo').val(hasVideo);\r\n");
      out.write("\t\t\t\t\t\t$('#experimentalProjectId').val(experimentalProjectId);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttitle : \"资料上传\",\r\n");
      out.write("\t\t\t\t\tclosed : false,\r\n");
      out.write("\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\tbuttons : [ //按钮\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttext : \"上传\",\r\n");
      out.write("\t\t\t\t\t\ticonCls : \"icon-ok\",\r\n");
      out.write("\t\t\t\t\t\thandler : upload\r\n");
      out.write("\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\ttext : '取消',\r\n");
      out.write("\t\t\t\t\t\ticonCls : \"icon-cancel\",\r\n");
      out.write("\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#video_dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction upload() {\r\n");
      out.write("\t\t\tdoAjaxc(\"/laboratoryweb/uploadVideo\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction doAjaxc(param) { //使用ajax方式\r\n");
      out.write("\t\t\tvar experProjectId = $(\"#experimentalProjectId\").val();\r\n");
      out.write("\t\t\tvar hasVideo = $(\"#hasVideo\").val();\r\n");
      out.write("\t\t\tvar video = $(\"#video\")[0].files[0];\r\n");
      out.write("\t\t\tvar learnfile = $(\"#learnfile\")[0].files[0];\r\n");
      out.write("\t\t\tvar formData = new FormData();\r\n");
      out.write("\t\t\tformData.append(\"experimentalProjectId\", experProjectId);\r\n");
      out.write("\t\t\tformData.append(\"hasVideo\", hasVideo);\r\n");
      out.write("\t\t\tformData.append(\"video\", video);\r\n");
      out.write("\t\t\tformData.append(\"learnfile\", learnfile);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : param,\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tdata : formData,\r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#video_dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#experProjectTable\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\tAlert(\"上传成功!\");\r\n");
      out.write("\t\t\t\t\t} else if (data == \"falseVideo\") {\r\n");
      out.write("\t\t\t\t\t\tAlert(\"实验视频非视频格式！\");\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tAlert(\"请重试!\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction tWatchVideo(id) {\r\n");
      out.write("\t\t\tvar rows = $(\"#experProjectTable\").datagrid(\"getRows\");\r\n");
      out.write("\t\t\tvar oneRow = rows[id];\r\n");
      out.write("\t\t\tvar experProjectPKID = oneRow[\"experProjectPKID\"];\r\n");
      out.write("\t\t\tvar experimentalProjectId = oneRow[\"experimentalProjectId\"];\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\tcache:false,\r\n");
      out.write("\t\t\t\turl : \"/laboratoryweb/getVideoAddress\",\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"experProjectPKID\" : experProjectPKID,\r\n");
      out.write("\t\t\t\t\t\"experimentalProjectId\" : experimentalProjectId\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif(data == \"fail\"){\r\n");
      out.write("\t\t\t\t\t\tAlert(\"视频不存在,请及时联系管理员\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#watchVideoid\"+id).css(\"target\",\"_blank\");\r\n");
      out.write("\t\t\t\t\t\twindow.location.href=\"/laboratoryweb/watchVideo\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
