/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-06 11:03:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page.teacher;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class t_002dstudy_002drecord_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<table id=\"studyRecordTable\" style=\"width: 100%; height: 100%;\" />\r\n");
      out.write("\t<div id=\"studyRecordtb\"></div>\r\n");
      out.write("\t<!-- 增加的提示框 -->\r\n");
      out.write("\t<div id=\"unPreStudyStu_dialog\" class=\"easyui-dialog\"\r\n");
      out.write("\t\tdata-options=\"closed:true,iconCls:'icon-save'\"\r\n");
      out.write("\t\tstyle=\"width: 410px; padding: 10px;\"></div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#studyRecordTable\")\r\n");
      out.write("\t\t\t\t\t.datagrid(\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : \"学生实验预习情况\",\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"/laboratoryweb/getPassOrderByAccount\",\r\n");
      out.write("\t\t\t\t\t\t\t\tpagination : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tstriped : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tpageSize : 15,\r\n");
      out.write("\t\t\t\t\t\t\t\tpageList : [ 15, 20 ],\r\n");
      out.write("\t\t\t\t\t\t\t\tcolumns : [ [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"orderPKID\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thidden : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"orderPKID\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"roomId\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"实验室\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"orderTime\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"预约时间\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 150\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"startTime\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"开始时间\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 150\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"endTime\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"结束时间\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 150\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"stuClass\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"班级\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"experProjectAccount\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"实验项目\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"preStudy\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"已完成预习人数/总人数\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 170,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tformatter : function(value, row,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tindex) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar num;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar data = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"orderPKID\" : row.orderPKID,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"stuClassId\" : row.stuClass\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata : data,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : \"/laboratoryweb/getPreStudyNum\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tnum = data.preStudyStuNum\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"/\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data.studentNum;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn num;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfield : \"  \",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttitle : \"未预习学生\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tformatter : function(value, row,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tindex) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar btn = '<a class=\"unPreStudy\" onclick=\"unPreStudy('\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ row.orderPKID\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ')\"  href=\"javascript:void(0)\"></a>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn btn;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyler : function(value, row, index) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t} ] ],\r\n");
      out.write("\t\t\t\t\t\t\t\tonLoadSuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('.unPreStudy').linkbutton({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttext : '学生信息',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplain : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticonCls : 'icon-serchar'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tsingleSelect : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tstriped : true,\r\n");
      out.write("\t\t\t\t\t\t\t\ttoolbar : \"#studyRecordtb\",\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t$(\"#seacherbutton\").click(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar dimWord = $(\"#dimSeacher\").textbox(\"getValue\");\r\n");
      out.write("\t\t\t\t\t\tvar queryParam = $(\"#studyRecordTable\").datagrid(\r\n");
      out.write("\t\t\t\t\t\t\t\t\"options\").queryParams;\r\n");
      out.write("\t\t\t\t\t\tqueryParam.dimWord = dimWord;\r\n");
      out.write("\t\t\t\t\t\t$(\"#studyRecordTable\").datagrid(\"load\");\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction unPreStudy(orderPKID) {\r\n");
      out.write("\t\t\tvar data = {\r\n");
      out.write("\t\t\t\t\"orderPKID\" : orderPKID,\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\turl : \"/laboratoryweb/setWatches\",\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\tdata : data,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#unPreStudyStu_dialog').dialog('refresh',\r\n");
      out.write("\t\t\t\t\t'/laboratoryweb/unPreStudyStu');\r\n");
      out.write("\t\t\t$(\"#unPreStudyStu_dialog\").dialog({\r\n");
      out.write("\t\t\t\tonOpen : function() {\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\ttitle : \"未预习学生列表\",\r\n");
      out.write("\t\t\t\tclosed : false,\r\n");
      out.write("\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\tbuttons : [ {\r\n");
      out.write("\t\t\t\t\ttext : '关闭',\r\n");
      out.write("\t\t\t\t\ticonCls : \"icon-cancel\",\r\n");
      out.write("\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t$(\"#unPreStudyStu_dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} ]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
